### ISSUE TITLE
add more activity query filters

### ISSUE THREAD

**Issue by ebrensi** [ebrensi/heatflask#60]
A few users requested more filters for activity import, in addition to the "last x activities", "date-range", etc.  Some ideas:
- activity type (running, cycling, swimming, ...)
- duration in time or distance
- average speed
- ??

**Comment by lijiayi0921** [comment]
Hi, Thanks a lot for your work and Heatflask is just an amazing tool of visualization of all my sport activities.
Is it possible to filter activities by type (running, biking, ...) , not necessarily for import, but for visualization ?

**Comment by ebrensi** [comment]
Hi @lijiayi0921!  In the current online version (v0.4.0) you can do this by sorting the activity table by activity-type by clicking on that table header, then selecting all of the activities of that activity-type, and then click the "Render selection" button.

I am integrating that functionality, along with some other features in the next release (v.0.5.0) that I want to have by the end of the year.

Maybe you can help. The main problem for me is the design.  Space in the text area is limited.  How can we tastefully arrange those controls without it looking too complicated?
I try to have the UI be as simple as possible.
Should there be a separate tab for those query/filter controls? Also, most of my users do not speak English.  I have a set of icons to represent different activities 
https://github.com/ebrensi/heatflask/tree/bundle/frontend/src/images/activity-icons
but I discovered that these icons just look too small.  I need to find ones that look good on a small screen.

Thanks for the interest!
